### ISSUE TITLE
Add main to bower entry

### ISSUE THREAD

**Issue by treygriffith** [Teleborder/FileSaver.js#2]
@mjrk, I'm tracking this here. Feel free to open a PR for this.

https://github.com/eligrey/FileSaver.js/pull/136#issuecomment-142643809 says:

> Could you add a main entry too?
> 
> ```
> "main": [
>   "Filesaver.js"
> ],
> ```

**Comment by mjrk** [comment]
see https://github.com/treygriffith/FileSaver.js/issues/1#issuecomment-143058618

Add

    "dependencies": {
      "file-saver": "Teleborder/FileSaver.js"
    }

to your bower.json to benefit from this repo.

Thanks!
